[package]
edition = "2024"
name = "blink"
rust-version = "1.95"
version = "0.1.0"

[[bin]]
name = "blink"
path = "../src/main.rs"

[features]
default = ["esp32c3"]
esp32c2 = ["esp-hal/esp32c2", "esp-bootloader-esp-idf/esp32c2", "esp-println/esp32c2", "esp-println/uart"]
esp32c3 = ["esp-hal/esp32c3", "esp-bootloader-esp-idf/esp32c3", "esp-println/esp32c3", "esp-println/jtag-serial"]
esp32c5 = ["esp-hal/esp32c5", "esp-bootloader-esp-idf/esp32c5", "esp-println/esp32c5", "esp-println/jtag-serial"]
esp32c6 = ["esp-hal/esp32c6", "esp-bootloader-esp-idf/esp32c6", "esp-println/esp32c6", "esp-println/jtag-serial"]
esp32h2 = ["esp-hal/esp32h2", "esp-bootloader-esp-idf/esp32h2", "esp-println/esp32h2", "esp-println/jtag-serial"]

[dependencies]
esp-hal = { version = "~1.2.2", default-features = false, features = ["rt"] }
esp-bootloader-esp-idf = { version = "0.6.0", default-features = false }
esp-println = { version = "0.18.0", default-features = false }
critical-section = "1.2.0"

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
lto = "fat"
opt-level = "s"
