"""Defaults and configuration for ESP32 development environment setup."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from esp32_dev.errors import SetupError

DEFAULT_IDF_VERSION = "latest"
DEFAULT_IDF_REPO = "https://github.com/espressif/esp-idf.git"
DEFAULT_IDF_TARGETS: tuple[str, ...] = ("esp32",)
DEFAULT_PREFIX_NAME = ".esp32-dev"
PARTIAL_SUFFIX = ".partial"
ESPTOOL_SPEC = "esptool"
PLATFORMIO_SPEC = "platformio"
MIN_PYTHON = (3, 10)
DIALOUT_GROUP = "dialout"

DEBIAN_PACKAGES: tuple[str, ...] = (
    "git",
    "wget",
    "flex",
    "bison",
    "gperf",
    "python3",
    "python3-pip",
    "python3-venv",
    "cmake",
    "ninja-build",
    "ccache",
    "libffi-dev",
    "libssl-dev",
    "dfu-util",
    "libusb-1.0-0",
)

FEDORA_PACKAGES: tuple[str, ...] = (
    "git",
    "wget",
    "flex",
    "bison",
    "gperf",
    "python3",
    "cmake",
    "ninja-build",
    "ccache",
    "dfu-util",
    "libusbx",
)

ARCH_PACKAGES: tuple[str, ...] = (
    "gcc",
    "git",
    "make",
    "flex",
    "bison",
    "gperf",
    "python",
    "cmake",
    "ninja",
    "ccache",
    "dfu-util",
    "libusb",
    "python-pip",
)

UDEV_RULES = """\
# USB serial / JTAG access for ESP32 boards (generated by esp32-dev)
# Silicon Labs CP210x
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE="0666", GROUP="dialout"
# QinHeng CH340
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", MODE="0666", GROUP="dialout"
# QinHeng CH9102 / CH342
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="55d4", MODE="0666", GROUP="dialout"
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="55d3", MODE="0666", GROUP="dialout"
# FTDI FT232
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", MODE="0666", GROUP="dialout"
# Espressif USB Serial/JTAG (ESP32-S2/S3/C3/C6 and similar)
SUBSYSTEM=="tty", ATTRS{idVendor}=="303a", MODE="0666", GROUP="dialout"
ATTRS{idVendor}=="303a", MODE="0666", GROUP="dialout"
"""


def default_prefix() -> Path:
    """Return the default installation prefix under the current user's home directory."""
    return Path.home() / DEFAULT_PREFIX_NAME


def default_udev_path() -> Path:
    """Return the default udev rules path."""
    return Path("/etc/udev/rules.d/99-esp32-dev.rules")


@dataclass
class SetupConfig:
    """User-selected options for a setup, status, or verify run."""

    prefix: Path
    idf_version: str = DEFAULT_IDF_VERSION
    idf_repo: str = DEFAULT_IDF_REPO
    idf_targets: tuple[str, ...] = DEFAULT_IDF_TARGETS
    skip_packages: bool = False
    skip_esptool: bool = False
    skip_platformio: bool = False
    skip_idf: bool = False
    skip_udev: bool = False
    skip_dialout: bool = False
    use_sudo: bool = True
    dry_run: bool = False
    force: bool = False
    shallow_idf: bool = True
    skip_shell: bool = False
    udev_rules_path: Path = field(default_factory=default_udev_path)

    def __post_init__(self) -> None:
        self.prefix = Path(self.prefix)
        self.udev_rules_path = Path(self.udev_rules_path)
        self.idf_version = self.idf_version.strip()
        self.idf_repo = self.idf_repo.strip()
        normalized = tuple(item.strip() for item in self.idf_targets if item.strip())
        if not normalized:
            raise SetupError("at least one ESP-IDF target is required")
        if not self.idf_version:
            raise SetupError("ESP-IDF version must not be empty")
        if not self.idf_repo:
            raise SetupError("ESP-IDF repository URL must not be empty")
        self.idf_targets = normalized

    @property
    def venv_dir(self) -> Path:
        """Python virtualenv that holds esptool and PlatformIO."""
        return self.prefix / "venv"

    @property
    def venv_python(self) -> Path:
        """Interpreter inside the tools virtualenv."""
        return self.venv_dir / "bin" / "python"

    @property
    def idf_dir(self) -> Path:
        """ESP-IDF clone directory."""
        return self.prefix / "esp-idf"

    @property
    def activate_script(self) -> Path:
        """POSIX shell script that activates IDF, esptool, and PlatformIO."""
        return self.prefix / "activate.sh"

    @property
    def activate_fish(self) -> Path:
        """Fish script that activates IDF, esptool, and PlatformIO."""
        return self.prefix / "activate.fish"

    @property
    def idf_partial_dir(self) -> Path:
        """Temporary directory used while cloning ESP-IDF."""
        return self.idf_dir.with_name(self.idf_dir.name + PARTIAL_SUFFIX)

    @property
    def venv_partial_dir(self) -> Path:
        """Temporary directory used while creating the tools virtualenv."""
        return self.venv_dir.with_name(self.venv_dir.name + PARTIAL_SUFFIX)

    @property
    def needs_venv(self) -> bool:
        """Whether a tools virtualenv should be created."""
        return not (self.skip_esptool and self.skip_platformio)
