"""Defaults and configuration for ESP32 development environment setup."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urlparse

from esp32_dev.errors import SetupError
from esp32_dev.pins import ESPTOOL_VERSION, IDF_VERSION, PLATFORMIO_VERSION

DEFAULT_IDF_VERSION = IDF_VERSION
DEFAULT_IDF_REPO = "https://github.com/espressif/esp-idf.git"
DEFAULT_IDF_TARGETS: tuple[str, ...] = ("esp32",)
DEFAULT_PREFIX_NAME = ".esp32-dev"
PARTIAL_SUFFIX = ".partial"
ESPTOOL_SPEC = f"esptool=={ESPTOOL_VERSION}"
PLATFORMIO_SPEC = f"platformio=={PLATFORMIO_VERSION}"
MIN_PYTHON = (3, 10)
DIALOUT_GROUP = "dialout"
RUSTUP_VERSION = "1.29.1"
RUSTUP_INIT_SHA256 = {
    "x86_64-unknown-linux-gnu": (
        "dda7234360b7f578ca8b0ddcb80145646fa61a67c1720a5abc7051b35c9fcb71"
    ),
    "aarch64-unknown-linux-gnu": (
        "15f6e4ce9f583b929c996c91562bad6d4454f3281de858b02cdfdef615fac433"
    ),
}
PIP_SPEC = "pip==25.2"
_IDF_REF = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._+/-]*$")
RUST_COMPONENTS: tuple[str, ...] = ("rust-src", "rustfmt", "clippy")
RISCV_TARGETS: tuple[str, ...] = (
    "riscv32imc-unknown-none-elf",
    "riscv32imac-unknown-none-elf",
)
CARGO_ESP_CRATES: tuple[str, ...] = (
    "ldproxy",
    "espflash",
    "cargo-espflash",
    "esp-generate",
)

DEBIAN_PACKAGES: tuple[str, ...] = (
    "git",
    "wget",
    "curl",
    "flex",
    "bison",
    "gperf",
    "python3",
    "python3-pip",
    "python3-venv",
    "cmake",
    "ninja-build",
    "ccache",
    "libffi-dev",
    "libssl-dev",
    "dfu-util",
    "libusb-1.0-0",
    "build-essential",
    "pkg-config",
    "libudev-dev",
)

FEDORA_PACKAGES: tuple[str, ...] = (
    "git",
    "wget",
    "curl",
    "flex",
    "bison",
    "gperf",
    "python3",
    "cmake",
    "ninja-build",
    "ccache",
    "dfu-util",
    "libusbx",
    "gcc",
    "gcc-c++",
    "perl",
    "pkgconf-pkg-config",
    "systemd-devel",
)

ARCH_PACKAGES: tuple[str, ...] = (
    "gcc",
    "git",
    "make",
    "flex",
    "bison",
    "gperf",
    "python",
    "cmake",
    "ninja",
    "ccache",
    "dfu-util",
    "libusb",
    "python-pip",
    "curl",
    "pkgconf",
)

UDEV_RULES = """\
# USB serial / JTAG access for ESP32 boards (generated by esp32-dev)
# Silicon Labs CP210x
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE="0660", GROUP="dialout"
# QinHeng CH340
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", MODE="0660", GROUP="dialout"
# QinHeng CH9102 / CH342
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="55d4", MODE="0660", GROUP="dialout"
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="55d3", MODE="0660", GROUP="dialout"
# FTDI FT232
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", MODE="0660", GROUP="dialout"
# Espressif USB Serial/JTAG (ESP32-S2/S3/C3/C6 and similar)
SUBSYSTEM=="tty", ATTRS{idVendor}=="303a", MODE="0660", GROUP="dialout"
"""


def default_prefix() -> Path:
    """Return the default installation prefix under the current user's home directory."""
    return Path.home() / DEFAULT_PREFIX_NAME


def rustup_triple(machine: str) -> str:
    """Return the rustup target triple for a Linux ``platform.machine()`` value."""
    normalized = {"amd64": "x86_64", "arm64": "aarch64"}.get(machine, machine)
    triple = f"{normalized}-unknown-linux-gnu"
    if triple not in RUSTUP_INIT_SHA256:
        raise SetupError(f"unsupported CPU for rustup-init: {machine}")
    return triple


def rustup_init_archive_url(triple: str) -> str:
    """Return the pinned rustup-init archive URL for ``triple``."""
    return f"https://static.rust-lang.org/rustup/archive/{RUSTUP_VERSION}/{triple}/rustup-init"


def validate_idf_version(version: str) -> str:
    """Reject ESP-IDF refs that could be interpreted as git options."""
    if _IDF_REF.fullmatch(version) is None:
        raise SetupError(f"invalid ESP-IDF version: {version}")
    return version


def validate_idf_repo(url: str) -> str:
    """Allow only https and git@ ESP-IDF repository URLs."""
    if url.startswith("-") or any(char in url for char in "\n\r\x00 "):
        raise SetupError(f"invalid ESP-IDF repository URL: {url}")
    if url.startswith("git@"):
        return url
    parsed = urlparse(url)
    if parsed.scheme != "https" or not parsed.netloc:
        raise SetupError("ESP-IDF repository must be an https or git@ URL")
    return url


def default_udev_path() -> Path:
    """Return the default udev rules path."""
    return Path("/etc/udev/rules.d/99-esp32-dev.rules")


@dataclass
class SetupConfig:
    """User-selected options for a setup, status, or verify run."""

    prefix: Path
    idf_version: str = DEFAULT_IDF_VERSION
    idf_repo: str = DEFAULT_IDF_REPO
    idf_targets: tuple[str, ...] = DEFAULT_IDF_TARGETS
    skip_packages: bool = False
    skip_esptool: bool = False
    skip_platformio: bool = False
    skip_idf: bool = False
    skip_rust: bool = False
    skip_udev: bool = False
    skip_dialout: bool = False
    use_sudo: bool = True
    dry_run: bool = False
    force: bool = False
    shallow_idf: bool = True
    skip_shell: bool = False
    udev_rules_path: Path = field(default_factory=default_udev_path)

    def __post_init__(self) -> None:
        self.prefix = Path(self.prefix)
        self.udev_rules_path = Path(self.udev_rules_path)
        self.idf_version = self.idf_version.strip()
        self.idf_repo = self.idf_repo.strip()
        normalized = tuple(item.strip() for item in self.idf_targets if item.strip())
        if not normalized:
            raise SetupError("at least one ESP-IDF target is required")
        if not self.idf_version:
            raise SetupError("ESP-IDF version must not be empty")
        if not self.idf_repo:
            raise SetupError("ESP-IDF repository URL must not be empty")
        self.idf_version = validate_idf_version(self.idf_version)
        self.idf_repo = validate_idf_repo(self.idf_repo)
        self.idf_targets = normalized

    @property
    def venv_dir(self) -> Path:
        """Python virtualenv that holds esptool and PlatformIO."""
        return self.prefix / "venv"

    @property
    def venv_python(self) -> Path:
        """Interpreter inside the tools virtualenv."""
        return self.venv_dir / "bin" / "python"

    @property
    def idf_dir(self) -> Path:
        """ESP-IDF clone directory."""
        return self.prefix / "esp-idf"

    @property
    def activate_script(self) -> Path:
        """POSIX shell script that activates IDF, esptool, PlatformIO, and Rust."""
        return self.prefix / "activate.sh"

    @property
    def activate_fish(self) -> Path:
        """Fish script that activates IDF, esptool, PlatformIO, and Rust."""
        return self.prefix / "activate.fish"

    @property
    def cargo_home(self) -> Path:
        """Cargo home (`CARGO_HOME`) inside the prefix."""
        return self.prefix / "cargo"

    @property
    def rustup_home(self) -> Path:
        """rustup home (`RUSTUP_HOME`) inside the prefix."""
        return self.prefix / "rustup"

    @property
    def cargo_bin(self) -> Path:
        """Directory that holds rustup, cargo, and ESP Rust cargo binaries."""
        return self.cargo_home / "bin"

    @property
    def export_esp_script(self) -> Path:
        """POSIX script generated by ``espup install`` for Xtensa env vars."""
        return self.prefix / "export-esp.sh"

    @property
    def idf_partial_dir(self) -> Path:
        """Temporary directory used while cloning ESP-IDF."""
        return self.idf_dir.with_name(self.idf_dir.name + PARTIAL_SUFFIX)

    @property
    def venv_partial_dir(self) -> Path:
        """Temporary directory used while creating the tools virtualenv."""
        return self.venv_dir.with_name(self.venv_dir.name + PARTIAL_SUFFIX)

    @property
    def needs_venv(self) -> bool:
        """Whether a tools virtualenv should be created."""
        return not (self.skip_esptool and self.skip_platformio)
