"""Activate scripts and interactive shell rc hooks."""

from __future__ import annotations

import logging
from pathlib import Path

from esp32_dev.config import SetupConfig
from esp32_dev.process import Host, Runner

logger = logging.getLogger("esp32_dev")

HOOK_BEGIN = "# >>> esp32-dev >>>"
HOOK_END = "# <<< esp32-dev <<<"

_RC_BY_SHELL = {
    "bash": ".bashrc",
    "zsh": ".zshrc",
    "fish": ".config/fish/config.fish",
    "ksh": ".kshrc",
    "mksh": ".kshrc",
    "pdksh": ".kshrc",
    "dash": ".profile",
    "sh": ".profile",
    "ash": ".profile",
}

_COMMON_RC = (
    ".bashrc",
    ".bash_profile",
    ".zshrc",
    ".zprofile",
    ".kshrc",
    ".profile",
    ".config/fish/config.fish",
)


def login_shell_name(shell_path: str) -> str:
    """Return the lowercase basename of a shell executable path."""
    return Path(shell_path).name.lower()


def generate_activate_script(config: SetupConfig) -> str:
    """Return POSIX shell that activates the tools virtualenv and ESP-IDF."""
    prefix = config.prefix
    return (
        "# Generated by esp32-dev. Do not edit.\n"
        'if [ -n "${ESP32_DEV_ACTIVE:-}" ]; then\n'
        "  return 0 2>/dev/null || exit 0\n"
        "fi\n"
        "ESP32_DEV_ACTIVE=1\n"
        f'export ESP32_DEV_PREFIX="{prefix}"\n'
        'if [ -f "$ESP32_DEV_PREFIX/venv/bin/activate" ]; then\n'
        "  # shellcheck disable=SC1091\n"
        '  . "$ESP32_DEV_PREFIX/venv/bin/activate"\n'
        "fi\n"
        'export IDF_PATH="$ESP32_DEV_PREFIX/esp-idf"\n'
        'if [ -n "${BASH_VERSION:-}${ZSH_VERSION:-}" ] && [ -f "$IDF_PATH/export.sh" ]; then\n'
        "  # ESP-IDF export.sh is bash-specific.\n"
        "  # shellcheck disable=SC1091\n"
        '  . "$IDF_PATH/export.sh"\n'
        "fi\n"
    )


def generate_activate_fish(config: SetupConfig) -> str:
    """Return fish shell that activates the tools virtualenv and ESP-IDF."""
    prefix = config.prefix
    return (
        "# Generated by esp32-dev. Do not edit.\n"
        "if set -q ESP32_DEV_ACTIVE\n"
        "    return\n"
        "end\n"
        "set -gx ESP32_DEV_ACTIVE 1\n"
        f'set -gx ESP32_DEV_PREFIX "{prefix}"\n'
        'if test -f "$ESP32_DEV_PREFIX/venv/bin/activate.fish"\n'
        '    source "$ESP32_DEV_PREFIX/venv/bin/activate.fish"\n'
        "end\n"
        'set -gx IDF_PATH "$ESP32_DEV_PREFIX/esp-idf"\n'
        'if test -f "$IDF_PATH/export.fish"\n'
        '    source "$IDF_PATH/export.fish"\n'
        "end\n"
    )


def generate_rc_hook(prefix: Path, rc: Path) -> str:
    """Return an interactive-only rc snippet for ``rc``."""
    if rc.name.endswith(".fish"):
        script = prefix / "activate.fish"
        return (
            f"{HOOK_BEGIN}\n"
            f'if status is-interactive; and test -f "{script}"\n'
            f'    source "{script}"\n'
            "end\n"
            f"{HOOK_END}\n"
        )
    script = prefix / "activate.sh"
    return f'{HOOK_BEGIN}\ncase $- in *i*) [ -f "{script}" ] && . "{script}" ;; esac\n{HOOK_END}\n'


def rc_files_to_hook(home: Path, shell_name: str) -> list[Path]:
    """Return rc files to update: login shell plus any existing common rc files."""
    targets: list[Path] = []
    relative = _RC_BY_SHELL.get(shell_name)
    if relative is not None:
        targets.append(home / relative)
    for rel in _COMMON_RC:
        path = home / rel
        if path.is_file() and path not in targets:
            targets.append(path)
    return targets


def upsert_hook(path: Path, block: str) -> None:
    """Insert or replace the marked hook block in ``path``."""
    existing = ""
    if path.is_file():
        existing = path.read_text(encoding="utf-8")
    start = existing.find(HOOK_BEGIN)
    end = existing.find(HOOK_END)
    snippet = block.rstrip("\n") + "\n"
    if start != -1 and end != -1 and end >= start:
        end += len(HOOK_END)
        if end < len(existing) and existing[end] == "\n":
            end += 1
        updated = existing[:start] + snippet + existing[end:]
    elif start != -1:
        updated = existing[:start] + snippet
    else:
        prefix = existing
        if prefix and not prefix.endswith("\n"):
            prefix += "\n"
        if prefix:
            prefix += "\n"
        updated = prefix + snippet
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(updated, encoding="utf-8")


def install_shell_hooks(config: SetupConfig, runner: Runner, host: Host) -> list[Path]:
    """Hook common interactive shells so they source the matching activate script."""
    if config.skip_shell:
        logger.info("skipping shell rc integration")
        return []
    name = login_shell_name(host.shell())
    targets = rc_files_to_hook(host.home(), name)
    if not targets:
        logger.warning(
            "no shell rc file to update for %s; source %s (or %s for fish)",
            host.shell(),
            config.activate_script,
            config.activate_fish,
        )
        return []
    if runner.dry_run:
        for rc in targets:
            logger.info("dry-run: hook %s", rc)
        return []
    hooked: list[Path] = []
    for rc in targets:
        upsert_hook(rc, generate_rc_hook(config.prefix, rc))
        logger.info("added shell hook to %s", rc)
        hooked.append(rc)
    return hooked
